Querdos\QPassDbBundle\Entity\QPassword:
    type:     entity
    table:    qpdb_qpassword
    repositoryClass: Querdos\QPassDbBundle\Repository\QPasswordRepository
    id:
        id:
            type:         integer
            id:           true
            generator:
                strategy: AUTO
    fields:
        label:
            type:         string
            length:       255
            nullable:     false
            unique:       false

        pass_id:
            type:         integer
            nullable:     false
            unique:       true

    manyToOne:
        qdatabase:
            targetEntity: Querdos\QPassDbBundle\Entity\QDatabase
            joinColumn:
                nullable: false