services:
    qpdb.util.pass_database:
        class: Querdos\QPassDbBundle\Util\PassDatabaseUtil
        calls:
            - [ setQDatabaseManager, [ '@qpdb.manager.qdatabase' ]]
            - [ setQPasswordManager, [ '@qpdb.manager.qpassword' ]]
