language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.6
          env: PHPUNIT_VERSION='^5.7'
        - php: 7.0
          env: PHPUNIT_VERSION='^6.1'

before_script:
    - curl -s http://getcomposer.org/installer | php --
    - php composer.phar install --dev
    - php composer.phar require symfony/symfony:dev-master
    - php composer.phar require symfony/framework-bundle:dev-master
    - php composer.phar require phpunit/phpunit:${PHPUNIT_VERSION}

script:
    - vendor/bin/phpunit
